'use strict';function w(f,a,b,d){f.A.pc(f.ab,a,b,d,void 0)}function E(f,a,b,d){f.A.ca?w(f,a,b,d):f.A.jf()._OnMessageFromDOM({type:"event",component:f.ab,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.A.C(f.ab,a,b)}function L(f,a){for(const [b,d]of a)J(f,b,d)}function M(f){f.Sb||(f.A.Ue(f.de),f.Sb=!0)}window.Sa=class{constructor(f,a){this.A=f;this.ab=a;this.Sb=!1;this.de=()=>this.Da()}hd(){}Da(){}};function N(f){-1!==f.Pa&&(self.clearTimeout(f.Pa),f.Pa=-1)}
window.Le=class{constructor(f,a){this.Oc=f;this.xg=a;this.Pa=-1;this.Tb=-Infinity;this.ee=()=>{this.Pa=-1;this.Tb=Date.now();this.gb=!0;this.Oc();this.gb=!1};this.Nd=this.gb=!1}c(){N(this);this.ee=this.Oc=null}};"use strict";function O(f,a){const b=a.elementId,d=f.md(b,a);f.Y.set(b,d);a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{P(f,"elem-focused",b)});d.addEventListener("blur",()=>{P(f,"elem-blurred",b)});f.Nb&&document.body.appendChild(d)}
function Q(f,a,b){J(f,a,d=>{const g=f.Y.get(d.elementId);return b(g,d)})}function P(f,a,b,d){d||(d={});d.elementId=b;w(f,a,d)}function R(f,a,b){var d;d||(d={});d.elementId=b;E(f,a,d)}
window.xe=class extends self.Sa{constructor(f,a){super(f,a);this.Y=new Map;this.Nb=!0;L(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Nb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Nb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Nb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.vc(d,b)}}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}md(){throw Error("required override");}vc(){throw Error("required override");}Ic(f){var a=this.Y.get(f.elementId);f.focus?a.focus():
a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Ig?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Mg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,g=!1;function n(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(m){}d=!0}return g}const p=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!p,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=
await x(m);return(new TextDecoder("utf-8")).decode(m)}function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=q=>c(q.target.result);l.onerror=q=>k(q);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.ma=class m{constructor(c){this.ca=
c.Og;this.pa=null;this.F="";this.cc=c.Lg;this.vb={};this.Ia=this.ub=null;this.Qb=[];this.jb=this.K=this.Na=null;this.Ma=-1;this.Cg=()=>this.Hf();this.La=[];this.s=c.fe;this.hb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ha=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.rf(k));this.C("runtime","create-job-worker",()=>this.sf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Ad(c)):this.Ad(c)}c(){this.wc();this.pa&&(this.pa=this.pa.onmessage=
null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Ge(){return f&&"cordova"===this.s}oc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Ad(c){"macos-wkwebview"===this.s&&this.Mc({type:"ready"});if("playable-ad"===this.s){this.ha=self.c3_base64files;this.Vb={};await this.Ze();for(let l=0,q=c.Qa.length;l<q;++l){var k=c.Qa[l].toLowerCase();
this.Vb.hasOwnProperty(k)?c.Qa[l]={Ig:!0,Mg:this.Vb[k]}:this.ha.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ha[k]))}}c.Dg?this.F=c.Dg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Qg&&(this.vb=c.Qg);k=new MessageChannel;this.pa=k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Df(l));this.jb=new self.He(this);await S(this.jb);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.lf(c,k.port2):await this.kf(c,k.port2)}zc(c){c=this.vb.hasOwnProperty(c)?this.vb[c]:c.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:"playable-ad"===this.s&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async ic(c,k,
l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.hb)return c=await this.wb(l.Hg?c:this.cc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}zd(c){var k=
this.jb;return{baseUrl:this.F,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Va(),projectData:c.Wg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Ug||"",exportType:c.fe,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Vg,jobScheduler:{inputPort:k.Uc,outputPort:k.ad,maxNumWorkers:k.zg},supportedAudioFormats:B,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Ge(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async lf(c,k){var l=this.zc(c.Pg);this.ub=await this.ic(l,this.F,{type:"module",name:"Runtime",Hg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);
window.c3canvas=this.K;let q=c.gd||[],u=c.Qa;q=await Promise.all(q.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.s)for(let r=0,t=c.fc.length;r<t;++r){const z=c.fc[r],H=z[0];if(H===c.ed||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(H)}this.ub.postMessage(Object.assign(this.zd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:q,engineScripts:u,projectScripts:c.fc,mainProjectScript:c.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...T(this.jb)]);this.Qb=F.map(r=>new r(this));this.yd();self.c3_callFunction=(r,t)=>this.Na.mf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.pc("runtime","go-to-last-error-script"))}async kf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=F.map(r=>new r(this));this.yd();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.gd)&&l.unshift(...c.gd);l=await Promise.all(l.map(r=>
this.Ea(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const q=c.ed,u=c.fc;for(let [r,t]of u)if(t||(t=r),r===q)try{t=await this.Ea(t),await b(t),"preview"!==this.s||l[r]||this.Id(r,"main script did not run to completion")}catch(z){this.Id(r,z)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await b(t);"preview"===this.s&&"object"!==typeof self.Rg.Sg?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.zd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:K}),this.Cd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Id(c,k){this.Ib();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Ib()}Ib(){const c=
window.Eg;c&&(c.parentElement.removeChild(c),window.Eg=null)}async sf(){const c=await U(this.jb);return{outputPort:c,transferables:[c]}}jf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}pc(c,k,l,q,u){this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:q||null,data:l,responseId:null},u)}rd(c,k,l,q,u){const r=I++,t=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:q||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.xf(c);if("result"===k)this.Kf(c);else if("runtime-ready"===k)this.Lf();else if("alert-error"===k)this.Ib(),alert(c.message);else if("creating-runtime"===k)this.Cd();else throw Error(`unknown message '${k}'`);}xf(c){const k=c.component,l=c.handler,q=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(q)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Hb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Hb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Hb(u,!1,""+t)}):this.Hb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Hb(c,k,l){let q;l&&l.transferables&&(q=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:k,result:l},q)}Kf(c){const k=c.responseId,l=c.isOk;c=c.result;const q=G.get(k);l?q.resolve(c):q.reject(c);G.delete(k)}C(c,
k,l){let q=A.get(c);q||(q=new Map,A.set(c,q));if(q.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);q.set(k,l)}static Ra(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}yd(){for(const c of this.Qb)if("runtime"===c.ab){this.Na=c;return}throw Error("cannot find runtime DOM handler");}Df(c){this.pc("debugger","message",c)}Lf(){for(const c of this.Qb)c.hd()}static Va(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Jb(c){h=!!c}Ue(c){this.La.push(c);this.Lc()}Yf(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.wc()}Lc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Cg))}wc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Hf(){this.Ma=-1;for(const c of this.La)c();this.Lc()}ua(c){this.Na.ua(c)}Ca(c){this.Na.Ca(c)}Kc(){this.Na.Kc()}Cb(c){this.Na.Cb(c)}Fe(){return!!B["audio/webm; codecs=opus"]}async vg(c){c=await this.rd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ee(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}qd(c){return!this.Ee(c)}async Ea(c){return"cordova"===this.s&&(c.startsWith("file:")||this.hb&&this.qd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.wb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async rf(c){const k=c.filename;switch(c.as){case "text":return await this.we(k);case "buffer":return await this.wb(k);
default:throw Error("unsupported type");}}ld(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,q)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,q)},q)})}async we(c){c=await this.ld(c);return await D(c)}xc(){if(y.length&&!(8<=C)){C++;var c=y.shift();this.$e(c.filename,c.Ng,c.Gg)}}wb(c){return new Promise((k,l)=>{y.push({filename:c,Ng:q=>{C--;this.xc();k(q)},Gg:q=>{C--;this.xc();l(q)}});this.xc()})}async $e(c,k,l){try{const q=await this.ld(c),u=await x(q);
k(u)}catch(q){l(q)}}Mc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ze(){const c=[];for(const [k,l]of Object.entries(this.ha))c.push(this.Ye(k,l));await Promise.all(c)}async Ye(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.gf(k);l||(l=
this.bf(k));this.ha[c]=l}}async gf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}bf(c){c=this.Sf(c);return this.Xe(c.data,c.Jg)}Sf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";
const q=k[2];l="base64"===k[1]||"base64"===q?atob(l):decodeURIComponent(l);return{Jg:c,data:l}}Xe(c,k){var l=c.length;let q=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,q),t,z;for(z=t=0;t<q;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const f=self.ma;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),q=k.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ra(class extends self.Sa{constructor(e){super(e,"runtime");this.Sd=!0;this.Oa=-1;this.cd="any";this.Jd=this.Kd=!1;this.Xc=
this.rb=this.ya=null;e.C("canvas","update-size",c=>this.Pf(c));e.C("runtime","invoke-download",c=>this.Bf(c));e.C("runtime","raster-svg-image",c=>this.If(c));e.C("runtime","get-svg-image-size",c=>this.zf(c));e.C("runtime","set-target-orientation",c=>this.Nf(c));e.C("runtime","register-sw",()=>this.Jf());e.C("runtime","post-to-debugger",c=>this.Ed(c));e.C("runtime","go-to-script",c=>this.Ed(c));e.C("runtime","before-start-ticking",()=>this.qf());e.C("runtime","debug-highlight",c=>this.tf(c));e.C("runtime",
"enable-device-orientation",()=>this.We());e.C("runtime","enable-device-motion",()=>this.Ve());e.C("runtime","add-stylesheet",c=>this.pf(c));e.C("runtime","alert",c=>this.Dc(c));e.C("runtime","hide-cordova-splash",()=>this.Af());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.ob=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Qf());window.addEventListener("fullscreenchange",
()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",c=>this.Fc(c));window.addEventListener("webkitfullscreenerror",c=>this.Fc(c));window.addEventListener("mozfullscreenerror",c=>this.Fc(c));e.oc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Rf(c);this.Ja=new Set;this.Wb=new WeakSet;this.oa=!1}qf(){"cordova"===this.A.s?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}hd(){window.addEventListener("focus",()=>
this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:K()});this.ob=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.Za("keyboard-blur")});window.addEventListener("keydown",h=>this.Dd("keydown",h));window.addEventListener("keyup",h=>this.Dd("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,d));window.addEventListener("wheel",h=>this.Ff(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Ac(h);this.Ya("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Le(()=>this.ef(),5),this.rb.Nd=!0,window.addEventListener("pointerrawupdate",h=>this.Gf(h))):window.addEventListener("pointermove",h=>this.Ya("pointermove",h)),window.addEventListener("pointerup",h=>this.Ya("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ya("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Ac(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Ac(h);this.Gb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Gb("pointermove",h)),window.addEventListener("touchend",h=>this.Gb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Gb("pointercancel",h)));const e=()=>this.Kc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Za(e,h){w(this,e,h||null,n)}wa(){return this.A.wa()}va(){return this.A.va()}Qf(){const e=this.wa(),h=this.va();this.Za("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()});this.A.oc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Fd(e,h,0))}Zf(e,h,m){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Fd(e,
h,m),48)}Fd(e,h,m){const c=this.wa(),k=this.va();this.Oa=-1;c!=e||k!=h?this.Za("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()}):10>m&&this.Zf(c,k,m+1)}Nf(e){this.cd=e.targetOrientation}rg(){const e=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Xa(){const e=f.Va();e&&"any"!==this.cd&&this.rg();w(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Fc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);w(this,"fullscreenerror",
{isFullscreen:f.Va(),innerWidth:this.wa(),innerHeight:this.va()})}Jc(e){e?this.A.wc():this.A.Lc();w(this,"visibilitychange",{hidden:e})}Dd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Ff(e){w(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Gc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Hc(e,h){if(!a(h)){var m=this.ob;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.ob=h.buttons;this.Gc(h.type,h,g)}}Ya(e,h){if(this.rb&&"pointermove"!==e){var m=this.rb;m.gb||(N(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.ob);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Gc(m,h,g),this.ob=h.buttons)}Gf(e){this.Xc=e;e=this.rb;if(-1===e.Pa){var h=Date.now(),m=h-e.Tb,c=e.xg;m>=c&&e.Nd?(e.Tb=h,e.gb=!0,e.Oc(),e.gb=!1):e.Pa=self.setTimeout(e.ee,Math.max(c-m,4))}}ef(){this.Ya("pointermove",this.Xc);this.Xc=null}Gb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Ac(e){window!==window.top&&window.focus();this.Bd(e.target)&&document.activeElement&&!this.Bd(document.activeElement)&&document.activeElement.blur()}Bd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}We(){this.Kd||(this.Kd=!0,window.addEventListener("deviceorientation",e=>this.vf(e)),window.addEventListener("deviceorientationabsolute",e=>this.wf(e)))}Ve(){this.Jd||(this.Jd=!0,window.addEventListener("devicemotion",e=>this.uf(e)))}vf(e){w(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}wf(e){w(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}uf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});w(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}Pf(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Sd&&(h.style.display="",this.Sd=!1)}Bf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async If(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async zf(e){return await self.C3_GetSvgImageSize(e.blob)}async pf(e){await p(e.url)}Kc(){var e=[...this.Ja];this.Ja.clear();if(!this.oa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Wb.has(h)||this.Ja.add(h)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Wb.delete(e);let h;try{h=e.play()}catch(m){this.Ja.add(e);return}h&&h.catch(()=>{this.Wb.has(e)||this.Ja.add(e)})}Ca(e){this.Ja.delete(e);
this.Wb.add(e)}Cb(e){this.oa=!!e}Af(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}tf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Jf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ed(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}mf(e,h){return this.A.rd(this.ab,"js-invoke-function",{name:e,params:h},void 0,void 0)}Dc(e){alert(e.message)}Rf(e){"entered-fullscreen"===e?(f.Jb(!0),this.Xa()):"exited-fullscreen"===e?(f.Jb(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function S(f){if(f.wg)throw Error("already initialised");f.wg=!0;var a=f.bc.zc("dispatchworker.js");f.Qc=await f.bc.ic(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Uc=a.port1;f.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.ad=await U(f)}function T(f){return[f.Uc,f.ad]}
async function U(f){const a=f.Td.length;var b=f.bc.zc("jobworker.js");b=await f.bc.ic(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Qc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Td.push(b);return g.port1}
self.He=class{constructor(f){this.bc=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.cc;this.zg=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.Td=[];this.ad=this.Uc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ma({Og:!0,Pg:"workermain.js",Qa:["scripts/c3runtime.js"],fc:[],ed:"",Lg:"scripts/",gd:[],fe:"html5"}));"use strict";
async function V(f,a){a=a.type;let b=!0;0===a?b=await W():1===a&&(b=await X());w(f,"permission-result",{type:a,result:b})}async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.ma.Ra(class extends self.Sa{constructor(f){super(f,"touch");J(this,"request-permission",a=>V(this,a))}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Sa{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Tc=!1;this.ra=()=>this.sg();this.aa=[];this.D=[];this.ga=null;this.Ud="";this.Vd=-1;this.qb=new Map;this.Yc=1;this.oa=!1;this.dd=0;this.dc=1;this.Rc=0;this.Xd="HRTF";this.Od="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.Qd=this.bd=!1;this.ce=this.A.Fe();this.ba=new Map;this.Ga=new Set;this.Vc=!1;this.Zc="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Ef(b,d);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.yf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.af(b)],["play",b=>this.Tf(b)],["stop",b=>this.pg(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.ig(b)],["set-volume",b=>this.ng(b)],["fade-volume",b=>this.ff(b)],["set-master-volume",b=>this.gg(b)],["set-muted",b=>this.hg(b)],["set-silent",b=>this.kg(b)],["set-looping",b=>this.fg(b)],["set-playback-rate",b=>this.jg(b)],["seek",b=>this.$f(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.tg(b)],["unload-all",()=>this.ug()],["set-suspended",b=>this.lg(b)],["add-effect",b=>this.wd(b)],["set-effect-param",b=>this.cg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Of(b)],["load-state",b=>this.Cf(b)]])}async af(a){a.isiOSCordova&&(this.bd=!0);this.dd=a.timeScaleMode;this.Xd=["equalpower","HRTF","soundfield"][a.panningModel];this.Od=["linear","inverse","exponential"][a.distanceModel];this.Yd=a.refDistance;this.Wd=a.maxDistance;this.$d=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.xd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.xd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.jc();try{await Promise.all(a.preloadList.map(d=>this.Eb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}xd(){this.Rb||(this.Tc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Rb=!0)}cf(){this.Rb&&(this.Tc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Rb=!1)}sg(){if(!this.Tc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.cf()}}W(){return this.f}jc(){return this.f.currentTime}sa(){return this.Pb}od(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.sa()}ge(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.eg(d.length);b.mg(a);d.push(b);this.Hd(a)}Hd(a){let b=this.sa();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const p=d[g];g+1===n?p.S(this.sa()):p.S(d[g+1].P())}}for(const g of this.la(a))g.Me(b);this.za&&this.Zc===a&&(this.za.disconnect(),this.za.connect(b))}yb(){return this.Yc}zb(){return this.oa}dg(){this.Qd=!0}ze(a,b){return b?this.A.vg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}ua(a){this.A.ua(a)}Ca(a){this.A.Ca(a)}sd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Ne(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.ta()?g.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.Ae(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Eb(a,b,d,g,n){for(const p of this.aa)if(p.Ua()===b)return await Y(p),
p;if(n)return null;g&&(this.bd||this.Qd)&&this.Ne();n="audio/webm; codecs=opus"===d&&!this.ce;g&&n&&this.dg();a=!g||this.bd||n?new self.ue(this,a,b,d,g,n):new self.se(this,a,b,d,g);this.aa.push(a);await Y(a);return a}async yc(a,b,d,g,n){for(const p of this.D)if(p.Ua()===b&&(p.hc()||n))return p.Pe(g),p;a=await this.Eb(a,b,d,n);g="html5"===a.Nc?new self.te(a.i,a,g):new self.ve(a.i,a,g);this.D.push(g);return g}Te(a){let b=this.qb.get(a);if(!b){let d=null;b={fd:0,Kg:new Promise(g=>d=g),resolve:d};this.qb.set(a,
b)}b.fd++}Xf(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.fd--;0===b.fd&&(b.resolve(),this.qb.delete(a))}uc(a){a||(a=this.Ud);return(a=this.qb.get(a))?a.Kg:Promise.resolve()}Fb(){if(0<this.Ga.size)M(this);else for(const a of this.D)if(a.pd()){M(this);break}}Da(){for(var a of this.Ga)a.Da();a=this.jc();for(var b of this.D)b.Da(a);b=this.D.filter(d=>d.pd()).map(d=>d.Ta());w(this,"state",{tickCount:this.Vd,audioInstances:b,analysers:[...this.Ga].map(d=>d.Ce())});0===b.length&&
0===this.Ga.size&&this.Sb&&(this.A.Yf(this.de),this.Sb=!1)}qc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async Tf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,p=a.tag,v=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Ud=p;this.Te(p);try{this.ga=await this.yc(b,d,g,p,n),x?(this.ga.Bb(!0),this.ga.Oe(x.x,x.y,x.angle,
x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ga.Qe(x.uid)):this.ga.Bb(!1),this.ga.Play(v,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Xf(p)}M(this)}pg(a){a=a.tag;for(const b of this.la(a))b.na()}qg(){for(const a of this.D)a.na()}ig(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Wa():d.Ab();this.Fb()}ng(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Db(a)}async ff(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.uc(b);for(const n of this.la(b))n.Be(d,g,a);this.Fb()}gg(a){this.Yc=a.vol;for(const b of this.D)b.Lb()}hg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.td(a)}kg(a){this.oa=a.isSilent;this.A.Cb(this.oa);for(const b of this.D)b.Kb()}fg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.sc(a)}async jg(a){const b=a.tag;a=a.rate;await this.uc(b);for(const d of this.la(b))d.vd(a)}async $f(a){const b=a.tag;a=a.pos;await this.uc(b);for(const d of this.la(b))d.rc(a)}async Uf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.yc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async tg(a){if(a=await this.Eb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}ug(){for(const a of this.aa)a.c();this.aa.length=0}lg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.tc(a);a&&this.f.suspend&&this.f.suspend()}Of(a){this.dc=a.timeScale;this.Rc=a.gameTime;this.Vd=a.tickCount;if(0!==
this.dd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.ud(d.x,d.y,d.angle)}}async wd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.me(this,...g);else if("delay"===b)g=new self.ke(this,...g);else if("convolution"===b){b=null;try{b=await this.Eb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.je(this,b.$,...g);g.ag(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ne(this,...g);else if("phaser"===b)g=new self.pe(this,...g);else if("gain"===b)g=new self.oe(this,...g);else if("tremolo"===b)g=new self.re(this,...g);else if("ringmod"===b)g=new self.qe(this,...g);else if("distortion"===b)g=new self.le(this,...g);else if("compressor"===b)g=new self.ie(this,...g);else if("analyser"===b)g=new self.he(this,...g);else throw Error("invalid effect type");this.ge(d,
g);this.Gd()}cg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,p),this.Gd())}Wf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Hd(a)}}Se(a){this.Ga.add(a);this.Fb()}Vf(a){this.Ga.delete(a)}Gd(){this.Vc||(this.Vc=!0,Promise.resolve().then(()=>this.df()))}df(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ta());w(this,"fxstate",{fxstate:a});this.Vc=!1}async Cf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ta()&&1===b||(d.ta()||2!==b)&&d.na();for(const g of this.ba.values())for(const n of g)n.c();this.ba.clear();this.dc=a.timeScale;this.Rc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.A.Cb(this.oa);this.Yc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.wd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.nf(g,b)));this.Fb()}async nf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,p=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.yc(d,g,n,v,p)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Ke(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Wa();b.Cc(a)}}}Ef(a,b){this.za&&this.za.disconnect();this.Zc=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.od(this.Zc))}yf(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),
this.Pb.connect(this.Ob));return this.Ob.stream}static Ae(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Re(a){return a*f}static ye(a){return Math.pow(10,a/20)}static nd(a){return Math.max(Math.min(self.da.ye(a),1),0)}static Je(a){return Math.log(a)/Math.log(10)*20}static Ie(a){return self.da.Je(Math.max(Math.min(a,1),0))}static Fg(a,b){return 1-Math.exp(-b*a)}};self.ma.Ra(self.da)}"use strict";function Y(f){f.Ub||(f.Ub=f.Bc());return f.Ub}
self.jd=class{constructor(f,a,b,d,g){this.i=f;this.Bg=a;this.Aa=b;this.R=d;this.yg=g;this.Nc="";this.Ub=null}c(){this.Ub=this.i=null}Bc(){}W(){return this.i.W()}lc(){return this.Bg}Ua(){return this.Aa}kc(){return this.R}ta(){return this.yg}ea(){}};"use strict";
self.se=class extends self.jd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Nc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.kb=this.lb=null;this.J.addEventListener("canplaythrough",()=>!0);this.pb=this.W().createGain();this.nb=null;this.J.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.J&&(this.nb=this.W().createMediaElementSource(this.J),this.nb.connect(this.pb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,n);this.kb&&(this.kb(n),this.kb=this.lb=null)})}c(){this.i.sd(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Bc(){return new Promise((f,a)=>{this.lb=f;this.kb=a;this.J.src=this.Aa})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function aa(f){if(f.xa)return f.xa;var a=f.i.A;if("cordova"===a.s&&a.qd(f.Aa)&&a.hb)f.xa=await a.wb(f.Aa);else{a=await fetch(f.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.xa=await a.arrayBuffer()}}async function ba(f){if(f.$)return f.$;f.$=await f.i.ze(f.xa,f.Ag);f.xa=null}
self.ue=class extends self.jd{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Nc="webaudio";this.$=this.xa=null;this.Ag=!!n}c(){this.i.sd(this);this.$=this.xa=null;super.c()}async Bc(){try{await aa(this),await ba(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.kd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Mb=f++;this.M=this.W().createGain();this.M.connect(this.sa());this.B=null;this.ib=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.tb=1;this.Ha=!1;this.qa=1;a=this.i.dd;this.Wc=1===a&&!this.ta()||2===a;this.eb=this.fa=-1;this.be=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.od(this.Z)}yb(){return this.i.yb()}xb(){return this.Wc?
this.i.Rc:performance.now()/1E3}lc(){return this.L.lc()}Ua(){return this.L.Ua()}kc(){return this.L.kc()}ta(){return this.L.ta()}Pe(a){this.Z=a}T(){}hc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}pd(){return!this.H&&!this.T()}Ba(){}ea(){return this.L.ea()}Play(){}na(){}Wa(){}Ab(){}Db(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.mc()}Be(a,b,d){if(!this.Ha){a*=this.yb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.jc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.be=d}}Lb(){this.Db(this.tb)}Da(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.be&&this.na(),this.i.qc("fade-ended",this.Z,this.Mb))}mc(){const a=this.tb*this.yb();return isFinite(a)?a:0}td(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Kb())}zb(){return this.i.zb()}Kb(){}sc(){}vd(a){this.qa!==a&&(this.qa=a,this.Fa())}Fa(){}rc(){}tc(){}Bb(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Xd,this.B.distanceModel=
this.i.Od,this.B.refDistance=this.i.Yd,this.B.maxDistance=this.i.Wd,this.B.rolloffFactor=this.i.$d),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.sa())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Oe(a,b,d,g,n,p){this.ib&&(this.ud(a,b,d),a=self.da.Re,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=p)}ud(a,b,d){this.ib&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Qe(a){this.fa=a}nc(){}Me(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Mb,tag:this.Z,duration:this.ea(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.qa,uid:this.fa,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.nc(),pan:this.De()}}Cc(a){this.vd(a.playbackRate);this.td(a.isMuted)}De(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ke(a){if(a){this.Bb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Bb(!1)}}}"use strict";
self.te=class extends self.kd{constructor(f,a,b){super(f,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Ec()}c(){this.na();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Ec(){this.H=!0;this.fa=-1;this.i.qc("ended",this.Z,this.Mb)}T(){return this.O().ended}hc(){return this.H?!0:this.T()}Ba(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Db(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,g)}this.i.ua(d);this.G=this.H=!1;this.V=f;this.qa=1}na(){const f=this.O();f.paused||f.pause();this.i.Ca(f);this.H=!0;this.G=!1;this.fa=-1}Wa(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ca(f);this.G=!0}}Ab(){!this.G||this.H||this.T()||(this.i.ua(this.O()),this.G=!1)}Kb(){this.O().muted=this.Ha||this.zb()}sc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Fa(){let f=this.qa;this.Wc&&(f*=this.i.dc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}rc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}nc(){return this.Ba()}tc(f){f?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ua(this.O()),this.ka=!1)}};"use strict";
function Z(f){f.j&&f.j.disconnect();f.j=null;f.$a=null}
self.ve=class extends self.kd{constructor(f,a,b){super(f,a,b);this.j=null;this.Xb=d=>this.Ec(d);this.Sc=!0;this.$a=null;this.N=this.Yb=this.Zb=0;this.$c=1}c(){this.na();Z(this);this.Xb=null;super.c()}Ec(f){this.G||this.ka||f.target!==this.$a||(this.H=this.Sc=!0,this.fa=-1,Z(this),this.i.qc("ended",this.Z,this.Mb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Sc}hc(){return!this.j||this.H?!0:this.T()}Ba(){let f;f=this.G?this.N:this.Yb+(this.xb()-this.Zb)*this.qa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.$c=1;this.Db(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.Xb;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Sc=!1;this.V=f;this.qa=1;this.Zb=this.xb();this.Yb=b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.fa=-1}Wa(){this.G||this.H||this.T()||(this.N=this.Ba(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Ab(){!this.G||this.H||this.T()||(Z(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.G=!1)}mc(){return super.mc()*this.$c}Kb(){this.$c=this.Ha||this.zb()?0:1;this.Lb()}sc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.qa;this.Wc&&(f*=this.i.dc);this.j&&(this.j.playbackRate.value=f)}rc(f){this.H||this.T()||(this.G?this.N=f:(this.Wa(),this.N=f,this.Ab()))}nc(){return this.N}tc(f){f?
this.IsPlaying()?(this.ka=!0,this.N=this.Ba(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.ka=!1)}Cc(f){super.Cc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Rd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}eg(a){this.Rd=a}mg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ta(){return{type:this.R,tag:this.Z,params:this.g}}}
self.me=class extends f{constructor(a,b,d,g,n,p,v){super(a);this.R="filter";this.g=[b,d,g,n,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=d;this.v.detune.value=g;this.v.Q.value=n;this.v.gain.vlaue=p;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,d,g)}}};self.ke=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=d;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.cb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.je=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Md=this.Ld="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.bb=this.f.createConvolver();this.bb.normalize=d;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}ag(a,b){this.Ld=a;this.Md=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Ld;a.bufferUrl="";a.bufferType=this.Md;return a}};self.ne=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="flanger";this.g=[b,d,g,n,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.u.connect(this.I);this.I.connect(this.U.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,d,g)}}};self.pe=class extends f{constructor(a,b,d,g,n,p,v){super(a);this.R="phaser";this.g=[b,d,g,n,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
d;this.v.Q.value=g;this.u=this.f.createOscillator();this.u.frequency.value=p;this.I=this.o();this.I.gain.value=n;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.u.connect(this.I);this.I.connect(this.v.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.v.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,g)}}};self.oe=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.nd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.re=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.u.connect(this.I);this.I.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.qe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.sb=this.o();this.sb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.sb.gain);this.u.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.le=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="distortion";this.g=[b,d,g,n,p];this.l=this.o();this.ac=this.o();this.$b=this.o();this.bg(g,n);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ec=this.f.createWaveShaper();this.Pc=new Float32Array(65536);this.hf(b,d);this.ec.curve=this.Pc;this.l.connect(this.ac);this.l.connect(this.a);this.ac.connect(this.ec);this.ec.connect(this.$b);
this.$b.connect(this.b)}c(){this.l.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.b.disconnect();this.a.disconnect();super.c()}bg(a,b){.01>a&&(a=.01);this.ac.gain.value=a;this.$b.gain.value=Math.pow(1/a,.6)*b}hf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.og(g,a,b);this.Pc[32768+d]=g;this.Pc[32768-d-1]=-g}}og(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Fg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="compressor";this.g=[b,d,g,n,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.he=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Pd=new Float32Array(this.h.frequencyBinCount);this.ae=new Uint8Array(b);this.Zd=this.Ka=0;this.i.Se(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Pd);this.h.getByteTimeDomainData(this.ae);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let g=(this.ae[d]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}d=self.da.Ie;this.Ka=d(this.Ka);this.Zd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ce(){return{tag:this.Z,index:this.Rd,peak:this.Ka,rms:this.Zd,binCount:this.h.frequencyBinCount,freqBins:this.Pd}}}}"use strict";function ca(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>w(f,"sw-message",a.data))}
function ea(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ma.Ra(class extends self.Sa{constructor(f){super(f,"browser");this.s="";L(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ca(this)],
["alert",a=>this.Dc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ea(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.Tg||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.ma.Jb(!0),this.A.Mc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.ma.Jb(!1),this.A.Mc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{w(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{w(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{w(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{w(this,"backbutton")})}Dc(f){alert(f.message)}Ic(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{function f(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.ma.Ra(class extends self.xe{constructor(b){super(b,"text-input");Q(this,"scroll-to-bottom",d=>this.Mf(d))}md(b,d){let g;const n=d.type;"textarea"===n?(g=document.createElement("textarea"),g.style.resize="none"):(g=document.createElement("input"),g.type=n);g.style.position="absolute";g.autocomplete="off";g.addEventListener("touchstart",f);g.addEventListener("touchmove",f);g.addEventListener("touchend",
f);g.addEventListener("mousedown",f);g.addEventListener("mouseup",f);g.addEventListener("keydown",a);g.addEventListener("keyup",a);g.addEventListener("click",p=>{p.stopPropagation();R(this,"click",b)});g.addEventListener("dblclick",p=>{p.stopPropagation();R(this,"dblclick",b)});g.addEventListener("input",()=>P(this,"change",b,{text:g.value}));d.id&&(g.id=d.id);this.vc(g,d);return g}vc(b,d){b.value=d.text;b.placeholder=d.placeholder;b.title=d.title;b.disabled=!d.isEnabled;b.readOnly=d.isReadOnly;b.spellcheck=
d.spellCheck;d=d.maxLength;0>d?b.removeAttribute("maxlength"):b.setAttribute("maxlength",d)}Mf(b){b.scrollTop=b.scrollHeight}})};
